package com.supermetroid.editor.headless

internal data class HeadlessBossBehaviorField(
    val key: String,
    val label: String,
    val snesAddress: Int,
    val defaultValue: Int,
    val category: String,
    val unit: String = "",
    val signed: Boolean = false,
    val hex: Boolean = false,
    val minValue: Int? = null,
    val maxValue: Int? = null,
    val writeSnesAddresses: List<Int> = listOf(snesAddress),
)

internal data class HeadlessBossBehaviorDefinition(
    val configType: String,
    val patchId: String,
    val name: String,
    val description: String,
    val fields: List<HeadlessBossBehaviorField>,
)

private fun headlessBossBehaviorField(
    key: String,
    label: String,
    snesAddress: Int,
    defaultValue: Int,
    category: String,
    unit: String = "",
    signed: Boolean = false,
    hex: Boolean = false,
    minValue: Int? = null,
    maxValue: Int? = null,
    additionalWriteAddresses: List<Int> = emptyList(),
): HeadlessBossBehaviorField =
    HeadlessBossBehaviorField(
        key = key,
        label = label,
        snesAddress = snesAddress,
        defaultValue = defaultValue,
        category = category,
        unit = unit,
        signed = signed,
        hex = hex,
        minValue = minValue,
        maxValue = maxValue,
        writeSnesAddresses = (listOf(snesAddress) + additionalWriteAddresses).distinct(),
    )

internal val HEADLESS_BOSS_BEHAVIOR_DEFINITIONS: List<HeadlessBossBehaviorDefinition> = listOf(
    HeadlessBossBehaviorDefinition(
        configType = PHANTOON_CONFIG_TYPE,
        patchId = "config_phantoon",
        name = "Phantoon",
        description = "Edit Phantoon vulnerability, closed, and hidden timers plus movement acceleration, velocity caps, wave motion, and phase positions. HP and contact damage remain in Boss Stats.",
        fields = listOf(
            headlessBossBehaviorField("vuln_0", "Round 0", 0xA7CD41, 0x003C, "Vulnerable Window - Eye Open Duration", unit = "frames"),
            headlessBossBehaviorField("vuln_1", "Round 1", 0xA7CD43, 0x001E, "Vulnerable Window - Eye Open Duration", unit = "frames"),
            headlessBossBehaviorField("vuln_2", "Round 2", 0xA7CD45, 0x000F, "Vulnerable Window - Eye Open Duration", unit = "frames"),
            headlessBossBehaviorField("vuln_3", "Round 3", 0xA7CD47, 0x001E, "Vulnerable Window - Eye Open Duration", unit = "frames"),
            headlessBossBehaviorField("vuln_4", "Round 4", 0xA7CD49, 0x003C, "Vulnerable Window - Eye Open Duration", unit = "frames"),
            headlessBossBehaviorField("vuln_5", "Round 5", 0xA7CD4B, 0x001E, "Vulnerable Window - Eye Open Duration", unit = "frames"),
            headlessBossBehaviorField("vuln_6", "Round 6", 0xA7CD4D, 0x000F, "Vulnerable Window - Eye Open Duration", unit = "frames"),
            headlessBossBehaviorField("vuln_7", "Round 7", 0xA7CD4F, 0x003C, "Vulnerable Window - Eye Open Duration", unit = "frames"),
            headlessBossBehaviorField("closed_0", "Round 0", 0xA7CD53, 0x02D0, "Eye Closed Duration - Between Patterns", unit = "frames"),
            headlessBossBehaviorField("closed_1", "Round 1", 0xA7CD55, 0x003C, "Eye Closed Duration - Between Patterns", unit = "frames"),
            headlessBossBehaviorField("closed_2", "Round 2", 0xA7CD57, 0x0168, "Eye Closed Duration - Between Patterns", unit = "frames"),
            headlessBossBehaviorField("closed_3", "Round 3", 0xA7CD59, 0x02D0, "Eye Closed Duration - Between Patterns", unit = "frames"),
            headlessBossBehaviorField("closed_4", "Round 4", 0xA7CD5B, 0x0168, "Eye Closed Duration - Between Patterns", unit = "frames"),
            headlessBossBehaviorField("closed_5", "Round 5", 0xA7CD5D, 0x003C, "Eye Closed Duration - Between Patterns", unit = "frames"),
            headlessBossBehaviorField("closed_6", "Round 6", 0xA7CD5F, 0x0168, "Eye Closed Duration - Between Patterns", unit = "frames"),
            headlessBossBehaviorField("closed_7", "Round 7", 0xA7CD61, 0x02D0, "Eye Closed Duration - Between Patterns", unit = "frames"),
            headlessBossBehaviorField("hide_0", "Round 0", 0xA7CD63, 0x003C, "Flame Rain - Hiding Duration", unit = "frames"),
            headlessBossBehaviorField("hide_1", "Round 1", 0xA7CD65, 0x0078, "Flame Rain - Hiding Duration", unit = "frames"),
            headlessBossBehaviorField("hide_2", "Round 2", 0xA7CD67, 0x001E, "Flame Rain - Hiding Duration", unit = "frames"),
            headlessBossBehaviorField("hide_3", "Round 3", 0xA7CD69, 0x003C, "Flame Rain - Hiding Duration", unit = "frames"),
            headlessBossBehaviorField("hide_4", "Round 4", 0xA7CD6B, 0x001E, "Flame Rain - Hiding Duration", unit = "frames"),
            headlessBossBehaviorField("hide_5", "Round 5", 0xA7CD6D, 0x003C, "Flame Rain - Hiding Duration", unit = "frames"),
            headlessBossBehaviorField("hide_6", "Round 6", 0xA7CD6F, 0x001E, "Flame Rain - Hiding Duration", unit = "frames"),
            headlessBossBehaviorField("hide_7", "Round 7", 0xA7CD71, 0x001E, "Flame Rain - Hiding Duration", unit = "frames"),
            headlessBossBehaviorField("fwd_accel_0", "Acceleration 0", 0xA7CD73, 0x0600, "Figure-8 Movement - Forward", hex = true),
            headlessBossBehaviorField("fwd_accel_1", "Acceleration 1", 0xA7CD75, 0x0000, "Figure-8 Movement - Forward", hex = true),
            headlessBossBehaviorField("fwd_accel_2", "Acceleration 2", 0xA7CD77, 0x1000, "Figure-8 Movement - Forward", hex = true),
            headlessBossBehaviorField("fwd_accel_3", "Acceleration 3", 0xA7CD79, 0x0000, "Figure-8 Movement - Forward", hex = true),
            headlessBossBehaviorField("fwd_cap_0", "Speed Cap 0", 0xA7CD7B, 0x0002, "Figure-8 Movement - Forward", unit = "steps/frame"),
            headlessBossBehaviorField("fwd_cap_1", "Speed Cap 1", 0xA7CD7D, 0x0007, "Figure-8 Movement - Forward", unit = "steps/frame"),
            headlessBossBehaviorField("fwd_cap_2", "Speed Cap 2", 0xA7CD7F, 0x0000, "Figure-8 Movement - Forward", unit = "steps/frame"),
            headlessBossBehaviorField("rev_accel_0", "Acceleration 0", 0xA7CD81, 0x0600, "Figure-8 Movement - Reverse", hex = true),
            headlessBossBehaviorField("rev_accel_1", "Acceleration 1", 0xA7CD83, 0x0000, "Figure-8 Movement - Reverse", hex = true),
            headlessBossBehaviorField("rev_accel_2", "Acceleration 2", 0xA7CD85, 0x1000, "Figure-8 Movement - Reverse", hex = true),
            headlessBossBehaviorField("rev_accel_3", "Acceleration 3", 0xA7CD87, 0x0000, "Figure-8 Movement - Reverse", hex = true),
            headlessBossBehaviorField("rev_cap_0", "Speed Cap 0", 0xA7CD89, 0xFFFE, "Figure-8 Movement - Reverse", unit = "steps/frame", signed = true),
            headlessBossBehaviorField("rev_cap_1", "Speed Cap 1", 0xA7CD8B, 0xFFF9, "Figure-8 Movement - Reverse", unit = "steps/frame", signed = true),
            headlessBossBehaviorField("rev_cap_2", "Speed Cap 2", 0xA7CD8D, 0x0000, "Figure-8 Movement - Reverse", unit = "steps/frame", signed = true),
            headlessBossBehaviorField("wave_amp", "Intro Amplitude Delta", 0xA7CD9B, 0x0040, "Wavy Effect - Intro / Death"),
            headlessBossBehaviorField("wave_freq", "Intro Max Amplitude", 0xA7CD9D, 0x0C00, "Wavy Effect - Intro / Death"),
            headlessBossBehaviorField("wave_growth", "Death Amplitude Delta", 0xA7CD9F, 0x0100, "Wavy Effect - Intro / Death"),
            headlessBossBehaviorField("wave_decay", "Death Max Amplitude", 0xA7CDA1, 0xF000, "Wavy Effect - Intro / Death", signed = true),
            headlessBossBehaviorField("wave_speed", "Wave Phase Delta", 0xA7CDA3, 0x0008, "Wavy Effect - Intro / Death"),
            headlessBossBehaviorField("pos0_x", "Position 0 X", 0xA7CDAF, 0x0080, "Flame Rain Positions", unit = "px"),
            headlessBossBehaviorField("pos0_y", "Position 0 Y", 0xA7CDB1, 0x0060, "Flame Rain Positions", unit = "px"),
            headlessBossBehaviorField("pos1_x", "Position 1 X", 0xA7CDB7, 0x00A8, "Flame Rain Positions", unit = "px"),
            headlessBossBehaviorField("pos1_y", "Position 1 Y", 0xA7CDB9, 0x0040, "Flame Rain Positions", unit = "px"),
            headlessBossBehaviorField("pos2_x", "Position 2 X", 0xA7CDBF, 0x00D0, "Flame Rain Positions", unit = "px"),
            headlessBossBehaviorField("pos2_y", "Position 2 Y", 0xA7CDC1, 0x0060, "Flame Rain Positions", unit = "px"),
            headlessBossBehaviorField("pos3_x", "Position 3 X", 0xA7CDC7, 0x00A8, "Flame Rain Positions", unit = "px"),
            headlessBossBehaviorField("pos3_y", "Position 3 Y", 0xA7CDC9, 0x0080, "Flame Rain Positions", unit = "px"),
        ),
    ),
    HeadlessBossBehaviorDefinition(
        configType = KRAID_CONFIG_TYPE,
        patchId = "config_kraid",
        name = "Kraid",
        description = "Edit Kraid lint timers, walking speed, intro and phase timers, earthquake cadence, falling rocks, and fingernail behavior. HP and contact damage remain in Boss Stats.",
        fields = listOf(
            headlessBossBehaviorField("lint_top_timer", "Top Lint Timer", 0xA7A916, 0x0120, "Kraid Constants", unit = "frames"),
            headlessBossBehaviorField("lint_middle_timer", "Middle Lint Timer", 0xA7A918, 0x00A0, "Kraid Constants", unit = "frames"),
            headlessBossBehaviorField("lint_bottom_timer", "Bottom Lint Timer", 0xA7A91A, 0x0040, "Kraid Constants", unit = "frames"),
            headlessBossBehaviorField("walk_forward_speed", "Forward Walk Speed", 0xA7A91C, 0x0003, "Kraid Constants", unit = "px/frame"),
            headlessBossBehaviorField("walk_back_speed", "Backward Walk Speed", 0xA7A920, 0x0003, "Kraid Constants", unit = "px/frame"),
            headlessBossBehaviorField("lint_x_subspeed", "Lint X Subspeed", 0xA7A926, 0x8000, "Kraid Constants", hex = true),
            headlessBossBehaviorField("lint_x_speed", "Lint X Speed", 0xA7A928, 0x0003, "Kraid Constants", unit = "px/frame"),
            headlessBossBehaviorField("intro_delay", "Intro Delay", 0xA7AA6A, 0x012C, "Intro And Phase Timers", unit = "frames"),
            headlessBossBehaviorField("initial_instruction_timer", "Initial Instruction Timer", 0xA7AA77, 0x0040, "Intro And Phase Timers", unit = "frames"),
            headlessBossBehaviorField("get_big_pause", "Get-Big Pause", 0xA7C016, 0x00B4, "Intro And Phase Timers", unit = "frames"),
            headlessBossBehaviorField("ceiling_rocks_slow_timer", "Slow Rock Phase", 0xA7C8A4, 0x0078, "Intro And Phase Timers", unit = "frames"),
            headlessBossBehaviorField("ceiling_rocks_fast_timer", "Fast Rock Phase", 0xA7C8F3, 0x0060, "Intro And Phase Timers", unit = "frames"),
            headlessBossBehaviorField("post_rise_foot_timer", "Post-Rise Foot Timer", 0xA7C973, 0x012C, "Intro And Phase Timers", unit = "frames"),
            headlessBossBehaviorField("mouth_close_timer", "After Mouth Closes", 0xA7AEF3, 0x005A, "Intro And Phase Timers", unit = "frames"),
            headlessBossBehaviorField("mouth_reopen_timer", "Mouth Reopen Delay", 0xA7AF15, 0x0040, "Intro And Phase Timers", unit = "frames"),
            headlessBossBehaviorField("earthquake_ceiling_mask", "Ceiling Quake Mask", 0xA7AC51, 0x0007, "Projectile Spawns", hex = true, maxValue = 0x00FF),
            headlessBossBehaviorField("earthquake_rise_slow_mask", "Rise Slow Quake Mask", 0xA7C8FA, 0x000F, "Projectile Spawns", hex = true, maxValue = 0x00FF),
            headlessBossBehaviorField("earthquake_rise_fast_mask", "Rise Fast Quake Mask", 0xA7C91C, 0x0007, "Projectile Spawns", hex = true, maxValue = 0x00FF),
            headlessBossBehaviorField("earthquake_shake_bit_mask", "Screen-Shake Spawn Mask", 0xA7C92B, 0x0005, "Projectile Spawns", hex = true, maxValue = 0x00FF),
            headlessBossBehaviorField("falling_rock_x_0", "Falling Rock X 0", 0xA7ACB3, 0x0068, "Projectile Spawns", unit = "px"),
            headlessBossBehaviorField("falling_rock_x_1", "Falling Rock X 1", 0xA7ACB5, 0x00D8, "Projectile Spawns", unit = "px"),
            headlessBossBehaviorField("falling_rock_x_2", "Falling Rock X 2", 0xA7ACB7, 0x0028, "Projectile Spawns", unit = "px"),
            headlessBossBehaviorField("falling_rock_x_3", "Falling Rock X 3", 0xA7ACB9, 0x00A8, "Projectile Spawns", unit = "px"),
            headlessBossBehaviorField("falling_rock_x_4", "Falling Rock X 4", 0xA7ACBB, 0x0058, "Projectile Spawns", unit = "px"),
            headlessBossBehaviorField("falling_rock_x_5", "Falling Rock X 5", 0xA7ACBD, 0x00C8, "Projectile Spawns", unit = "px"),
            headlessBossBehaviorField("falling_rock_x_6", "Falling Rock X 6", 0xA7ACBF, 0x0038, "Projectile Spawns", unit = "px"),
            headlessBossBehaviorField("falling_rock_x_7", "Falling Rock X 7", 0xA7ACC1, 0x00B8, "Projectile Spawns", unit = "px"),
            headlessBossBehaviorField("falling_rock_x_8", "Falling Rock X 8", 0xA7ACC3, 0x0048, "Projectile Spawns", unit = "px"),
            headlessBossBehaviorField("good_fingernail_timer", "Good Fingernail Timer", 0xA7AE5F, 0x0040, "Fingernails", unit = "frames"),
            headlessBossBehaviorField("bad_fingernail_timer", "Bad Fingernail Timer", 0xA7AE65, 0x0080, "Fingernails", unit = "frames"),
            headlessBossBehaviorField("horizontal_nail_x", "Horizontal Nail X", 0xA7BE04, 0x0032, "Fingernails", unit = "px"),
            headlessBossBehaviorField("horizontal_nail_y", "Horizontal Nail Y", 0xA7BE0A, 0x00F0, "Fingernails", unit = "px"),
            headlessBossBehaviorField("horizontal_nail_x_speed", "Horizontal Nail X Speed", 0xA7BE16, 0x0001, "Fingernails", unit = "px/frame"),
            headlessBossBehaviorField("horizontal_nail_y_speed", "Horizontal Nail Y Speed", 0xA7BE22, 0x0000, "Fingernails", unit = "px/frame", signed = true),
            headlessBossBehaviorField("diagonal_up_x_speed", "Diagonal Up X Speed", 0xA7BE50, 0xFFFF, "Fingernails", unit = "px/frame", signed = true, additionalWriteAddresses = listOf(0xA7BE60, 0xA7BE70, 0xA7BE80)),
            headlessBossBehaviorField("diagonal_up_y_speed", "Diagonal Up Y Speed", 0xA7BE54, 0x0001, "Fingernails", unit = "px/frame", signed = true, additionalWriteAddresses = listOf(0xA7BE64, 0xA7BE74, 0xA7BE84)),
            headlessBossBehaviorField("diagonal_down_x_speed", "Diagonal Down X Speed", 0xA7BE58, 0xFFFF, "Fingernails", unit = "px/frame", signed = true, additionalWriteAddresses = listOf(0xA7BE68, 0xA7BE78, 0xA7BE88)),
            headlessBossBehaviorField("diagonal_down_y_speed", "Diagonal Down Y Speed", 0xA7BE5C, 0xFFFF, "Fingernails", unit = "px/frame", signed = true, additionalWriteAddresses = listOf(0xA7BE6C, 0xA7BE7C, 0xA7BE8C)),
        ),
    ),
    HeadlessBossBehaviorDefinition(
        configType = RIDLEY_CONFIG_TYPE,
        patchId = "config_ridley",
        name = "Ridley",
        description = "Edit Ridley's intro timers, arena bounds, Ceres attacks, Norfair swoop, hover, and pogo constants. HP and contact damage remain in Boss Stats.",
        fields = listOf(
            headlessBossBehaviorField("ceres_intro_delay", "Ceres Intro Delay", 0xA6A367, 0x0200, "Intro And Fade-In", unit = "frames"),
            headlessBossBehaviorField("norfair_intro_delay", "Norfair Intro Delay", 0xA6A372, 0x00AA, "Intro And Fade-In", unit = "frames"),
            headlessBossBehaviorField("eye_fade_step_delay", "Eye Fade Step Delay", 0xA6A396, 0x0001, "Intro And Fade-In", unit = "frames"),
            headlessBossBehaviorField("body_fade_step_delay", "Body Fade Step Delay", 0xA6A3E6, 0x0002, "Intro And Fade-In", unit = "frames"),
            headlessBossBehaviorField("wait_to_roar_timer", "Wait To Roar", 0xA6A448, 0x0004, "Intro And Fade-In", unit = "frames"),
            headlessBossBehaviorField("ceres_roar_timer", "Ceres Roar Timer", 0xA6A472, 0x00FC, "Intro And Fade-In", unit = "frames"),
            headlessBossBehaviorField("norfair_background_fade_timer", "Norfair BG Fade Timer", 0xA6A486, 0x0002, "Intro And Fade-In", unit = "frames"),
            headlessBossBehaviorField("transition_wing_timer", "Transition Wing Timer", 0xA6A4BB, 0x0008, "Intro And Fade-In", unit = "frames"),
            headlessBossBehaviorField("norfair_initial_x", "Norfair Initial X", 0xA6A171, 0x0060, "Arena And Tail Damage", unit = "px"),
            headlessBossBehaviorField("norfair_initial_y", "Norfair Initial Y", 0xA6A177, 0x018A, "Arena And Tail Damage", unit = "px"),
            headlessBossBehaviorField("norfair_min_y", "Norfair Minimum Y", 0xA6A19E, 0x0040, "Arena And Tail Damage", unit = "px"),
            headlessBossBehaviorField("norfair_max_y", "Norfair Maximum Y", 0xA6A1A5, 0x01A0, "Arena And Tail Damage", unit = "px"),
            headlessBossBehaviorField("norfair_min_x", "Norfair Minimum X", 0xA6A1AC, 0x0040, "Arena And Tail Damage", unit = "px"),
            headlessBossBehaviorField("norfair_max_x", "Norfair Maximum X", 0xA6A1B3, 0x00E0, "Arena And Tail Damage", unit = "px"),
            headlessBossBehaviorField("norfair_tail_damage", "Norfair Tail Damage", 0xA6A1C1, 0x0078, "Arena And Tail Damage", unit = "damage"),
            headlessBossBehaviorField("ceres_tail_damage", "Ceres Tail Damage", 0xA6A217, 0x000F, "Arena And Tail Damage", unit = "damage"),
            headlessBossBehaviorField("ceres_liftoff_accel", "Liftoff Up Accel", 0xA6A6B4, 0xFFF0, "Ceres Attacks", unit = "subpx/frame", signed = true),
            headlessBossBehaviorField("ceres_liftoff_decel", "Liftoff Down Accel", 0xA6A6CD, 0x0014, "Ceres Attacks", unit = "subpx/frame", signed = true),
            headlessBossBehaviorField("ceres_hover_cooldown", "Hover Attack Cooldown", 0xA6A728, 0x007C, "Ceres Attacks", unit = "frames"),
            headlessBossBehaviorField("ceres_hover_target_x", "Hover Target X", 0xA6A764, 0x00C0, "Ceres Attacks", unit = "px"),
            headlessBossBehaviorField("ceres_hover_target_y", "Hover Target Y", 0xA6A767, 0x0064, "Ceres Attacks", unit = "px"),
            headlessBossBehaviorField("ceres_fireball_target_y", "Fireball Target Y", 0xA6A7A5, 0x0058, "Ceres Attacks", unit = "px"),
            headlessBossBehaviorField("ceres_fireball_timer", "Fireball Timer", 0xA6A7DA, 0x00E0, "Ceres Attacks", unit = "frames"),
            headlessBossBehaviorField("ceres_forced_swoop_delay", "Forced Swoop Delay", 0xA6A7EE, 0x0030, "Ceres Attacks", unit = "frames"),
            headlessBossBehaviorField("ceres_lunge_timer", "Lunge Setup Timer", 0xA6A849, 0x0040, "Ceres Attacks", unit = "frames"),
            headlessBossBehaviorField("ceres_lunge_y_offset", "Lunge Y Offset", 0xA6A858, 0x0044, "Ceres Attacks", unit = "px"),
            headlessBossBehaviorField("ceres_lunge_min_y", "Lunge Minimum Y", 0xA6A860, 0x0040, "Ceres Attacks", unit = "px"),
            headlessBossBehaviorField("ceres_lunge_accel_factor", "Lunge Accel Factor", 0xA6A868, 0x000D, "Ceres Attacks"),
            headlessBossBehaviorField("norfair_low_health_threshold", "Low Health Threshold", 0xA6B35B, 0x3840, "Norfair Swoop And Hover", unit = "hp"),
            headlessBossBehaviorField("norfair_secondary_low_health_threshold", "Secondary Low Health", 0xA6B382, 0x2328, "Norfair Swoop And Hover", unit = "hp"),
            headlessBossBehaviorField("norfair_swoop_start_timer", "Swoop Start Timer", 0xA6B485, 0x0020, "Norfair Swoop And Hover", unit = "frames"),
            headlessBossBehaviorField("norfair_swoop_down_timer", "Swoop Down Timer", 0xA6B4CA, 0x0014, "Norfair Swoop And Hover", unit = "frames"),
            headlessBossBehaviorField("norfair_swoop_horizontal_timer", "Swoop Horizontal Timer", 0xA6B508, 0x0010, "Norfair Swoop And Hover", unit = "frames"),
            headlessBossBehaviorField("norfair_swoop_up_timer", "Swoop Up Timer", 0xA6B54D, 0x0020, "Norfair Swoop And Hover", unit = "frames"),
            headlessBossBehaviorField("norfair_swoop_decel_timer", "Swoop Decel Timer", 0xA6B58B, 0x0020, "Norfair Swoop And Hover", unit = "frames"),
            headlessBossBehaviorField("norfair_swoop_down_speed", "Swoop Down Speed", 0xA6B4B0, 0x0480, "Norfair Swoop And Hover", unit = "speed"),
            headlessBossBehaviorField("norfair_swoop_horizontal_speed", "Swoop Horizontal Speed", 0xA6B4EE, 0x0500, "Norfair Swoop And Hover", unit = "speed"),
            headlessBossBehaviorField("norfair_swoop_up_speed", "Swoop Up Speed", 0xA6B533, 0x0300, "Norfair Swoop And Hover", unit = "speed"),
            headlessBossBehaviorField("norfair_swoop_fast_up_speed", "Fast Up Speed", 0xA6B571, 0x0300, "Norfair Swoop And Hover", unit = "speed"),
            headlessBossBehaviorField("norfair_swoop_decel_speed", "Decel Speed", 0xA6B59C, 0x01C0, "Norfair Swoop And Hover", unit = "speed"),
            headlessBossBehaviorField("norfair_hover_timer_base", "Hover Timer Base", 0xA6B5E0, 0x0020, "Norfair Swoop And Hover", unit = "frames"),
            headlessBossBehaviorField("norfair_hover_wall_timer", "Hover Wall Timer", 0xA6B604, 0x0080, "Norfair Swoop And Hover", unit = "frames", additionalWriteAddresses = listOf(0xA6B632)),
            headlessBossBehaviorField("norfair_hover_target_y_cap", "Hover Target Y Cap", 0xA6B645, 0x0160, "Norfair Swoop And Hover", unit = "px"),
            headlessBossBehaviorField("norfair_hover_fireball_threshold", "Hover Fireball Threshold", 0xA6B670, 0x0080, "Norfair Swoop And Hover", hex = true),
            headlessBossBehaviorField("pogo_tail_extension_speed", "Tail Extension Speed", 0xA6B68C, 0x00F0, "Norfair Pogo", unit = "speed"),
            headlessBossBehaviorField("pogo_tail_angle", "Tail Segment Angle", 0xA6B693, 0x0010, "Norfair Pogo", hex = true),
            headlessBossBehaviorField("pogo_target_y", "Pogo Target Y", 0xA6B6AB, 0x0120, "Norfair Pogo", unit = "px", additionalWriteAddresses = listOf(0xA6B6BB, 0xA6B6E3)),
            headlessBossBehaviorField("pogo_wait_timer", "Pogo Wait Timer", 0xA6B6D8, 0x0020, "Norfair Pogo", unit = "frames"),
            headlessBossBehaviorField("pogo_ascending_timer_base", "Ascending Timer Base", 0xA6B708, 0x0080, "Norfair Pogo", unit = "frames"),
            headlessBossBehaviorField("pogo_max_down_velocity", "Max Down Velocity", 0xA6B723, 0x0600, "Norfair Pogo", unit = "speed"),
            headlessBossBehaviorField("pogo_fireball_counter", "Fireball Counter", 0xA6B79A, 0x0002, "Norfair Pogo"),
        ),
    ),
    HeadlessBossBehaviorDefinition(
        configType = DRAYGON_CONFIG_TYPE,
        patchId = "config_draygon",
        name = "Draygon",
        description = "Edit Draygon's intro, swoop, goop, grab, spiral, foam, and bubble constants from bank A5. HP and contact damage remain in Boss Stats.",
        fields = listOf(
            headlessBossBehaviorField("intro_delay", "Intro Delay", 0xA58725, 0x0100, "Intro And Swoop", unit = "frames"),
            headlessBossBehaviorField("intro_dance_duration", "Intro Dance Duration", 0xA58795, 0x04D0, "Intro And Swoop", unit = "frames"),
            headlessBossBehaviorField("swoop_y_acceleration", "Swoop Y Acceleration", 0xA58784, 0x0018, "Intro And Swoop", unit = "subpx/frame"),
            headlessBossBehaviorField("turret_projectile_speed", "Wall Turret Speed", 0xA587D5, 0x0003, "Intro And Swoop", unit = "px/frame"),
            headlessBossBehaviorField("right_reset_x_offset", "Right Reset X Offset", 0xA58768, 0x02A0, "Intro And Swoop", unit = "px"),
            headlessBossBehaviorField("swoop_initial_y", "Swoop Initial Y", 0xA58818, 0x0180, "Intro And Swoop", unit = "px"),
            headlessBossBehaviorField("swoop_table_max_index", "Swoop Table Max Index", 0xA58863, 0x0800, "Intro And Swoop", hex = true),
            headlessBossBehaviorField("arm_apex_index", "Arm Apex Index", 0xA588BE, 0x0068, "Intro And Swoop", hex = true, additionalWriteAddresses = listOf(0xA5895B, 0xA58A0D, 0xA58A9D)),
            headlessBossBehaviorField("goop_right_start_x", "Right Start X", 0xA58B0E, 0xFFB0, "Goop Runs", unit = "px", signed = true),
            headlessBossBehaviorField("goop_start_y", "Start Y", 0xA58B14, 0x0180, "Goop Runs", unit = "px", additionalWriteAddresses = listOf(0xA58C96)),
            headlessBossBehaviorField("goop_x_speed", "X Speed", 0xA58B20, 0x0001, "Goop Runs", unit = "px/frame", additionalWriteAddresses = listOf(0xA58CA2)),
            headlessBossBehaviorField("goop_range_to_samus", "Samus Range", 0xA58B64, 0x00D0, "Goop Runs", unit = "px", additionalWriteAddresses = listOf(0xA58CE6)),
            headlessBossBehaviorField("goop_count", "Goop Counter", 0xA58B6F, 0x0010, "Goop Runs", additionalWriteAddresses = listOf(0xA58CF1)),
            headlessBossBehaviorField("goop_y_radius", "Y Oscillation Radius", 0xA58B77, 0x0020, "Goop Runs", unit = "px", additionalWriteAddresses = listOf(0xA58BD6, 0xA58C37, 0xA58CF9, 0xA58D55, 0xA58DBB)),
            headlessBossBehaviorField("goop_base_y", "Y Oscillation Base", 0xA58B86, 0x0180, "Goop Runs", unit = "px", additionalWriteAddresses = listOf(0xA58BE5, 0xA58C46, 0xA58D08, 0xA58D64, 0xA58DCA)),
            headlessBossBehaviorField("goop_angle_step", "Y Angle Step", 0xA58B91, 0x0001, "Goop Runs", hex = true, additionalWriteAddresses = listOf(0xA58BF0, 0xA58C51, 0xA58D13, 0xA58D6F, 0xA58DD5)),
            headlessBossBehaviorField("goop_right_boundary", "Right Offscreen Boundary", 0xA58C0F, 0x02A0, "Goop Runs", unit = "px", additionalWriteAddresses = listOf(0xA58C70)),
            headlessBossBehaviorField("goop_left_boundary", "Left Offscreen Boundary", 0xA58D8E, 0xFFB0, "Goop Runs", unit = "px", signed = true, additionalWriteAddresses = listOf(0xA58DF4)),
            headlessBossBehaviorField("grab_proximity", "Grab Proximity", 0xA58E4B, 0x0008, "Grab And Spiral", unit = "px", additionalWriteAddresses = listOf(0xA58E5B)),
            headlessBossBehaviorField("chase_speed", "Chase Speed", 0xA58E88, 0x0002, "Grab And Spiral", unit = "px/frame"),
            headlessBossBehaviorField("spiral_initial_x", "Spiral Initial X", 0xA58EDC, 0x0100, "Grab And Spiral", unit = "px"),
            headlessBossBehaviorField("spiral_initial_y", "Spiral Initial Y", 0xA58EE3, 0x0180, "Grab And Spiral", unit = "px"),
            headlessBossBehaviorField("spiral_initial_angle", "Spiral Initial Angle", 0xA58EF5, 0x00C0, "Grab And Spiral", hex = true),
            headlessBossBehaviorField("spiral_angle_delta", "Spiral Angle Delta", 0xA58EFC, 0x0800, "Grab And Spiral", hex = true),
            headlessBossBehaviorField("center_target_x", "Center Target X", 0xA58F48, 0x0100, "Grab And Spiral", unit = "px"),
            headlessBossBehaviorField("center_target_y", "Center Target Y", 0xA58F58, 0x0180, "Grab And Spiral", unit = "px"),
            headlessBossBehaviorField("center_tolerance", "Center Tolerance", 0xA58F4F, 0x0002, "Grab And Spiral", unit = "px", additionalWriteAddresses = listOf(0xA58F5F)),
            headlessBossBehaviorField("center_move_speed", "Center Move Speed", 0xA58F8C, 0x0002, "Grab And Spiral", unit = "px/frame"),
            headlessBossBehaviorField("tail_whip_random_mask", "Tail Whip Random Mask", 0xA58FFF, 0x00FF, "Grab And Spiral", hex = true),
            headlessBossBehaviorField("tail_whip_timer", "Tail Whip Timer", 0xA59004, 0x0040, "Grab And Spiral", unit = "frames"),
            headlessBossBehaviorField("spiral_radius_increment", "Radius Increment", 0xA5907B, 0x2000, "Grab And Spiral", hex = true),
            headlessBossBehaviorField("spiral_max_radius", "Max Radius", 0xA5908D, 0x00A0, "Grab And Spiral", unit = "px"),
            headlessBossBehaviorField("spiral_angle_delta_decay", "Angle Delta Decay", 0xA59097, 0x0001, "Grab And Spiral", hex = true),
            headlessBossBehaviorField("spiral_y_substep", "Y Substep", 0xA590B3, 0x4000, "Grab And Spiral", hex = true),
            headlessBossBehaviorField("final_tail_whip_y_threshold", "Final Tail-Whip Y", 0xA590C5, 0x0040, "Grab And Spiral", unit = "px"),
            headlessBossBehaviorField("fly_up_speed", "Fly-Up Speed", 0xA5915C, 0x0004, "Grab And Spiral", unit = "px/frame"),
            headlessBossBehaviorField("foam_frequency_mask", "Foam Frequency Mask", 0xA59045, 0x0007, "Foam And Bubbles", hex = true),
            headlessBossBehaviorField("foam_x_offset", "Foam X Offset", 0xA5904E, 0x0020, "Foam And Bubbles", unit = "px", additionalWriteAddresses = listOf(0xA5905D)),
            headlessBossBehaviorField("foam_y_offset", "Foam Y Offset", 0xA59066, 0x0010, "Foam And Bubbles", unit = "px"),
            headlessBossBehaviorField("breath_bubble_mask", "Breath Bubble Mask", 0xA59320, 0x007F, "Foam And Bubbles", hex = true),
            headlessBossBehaviorField("breath_bubble_x_offset", "Breath Bubble X Offset", 0xA59329, 0xFFF0, "Foam And Bubbles", unit = "px", signed = true),
            headlessBossBehaviorField("breath_bubble_y_offset", "Breath Bubble Y Offset", 0xA59332, 0xFFF0, "Foam And Bubbles", unit = "px", signed = true),
        ),
    ),
    HeadlessBossBehaviorDefinition(
        configType = SPORE_SPAWN_CONFIG_TYPE,
        patchId = "config_spore_spawn",
        name = "Spore Spawn",
        description = "Edit Spore Spawn's orbit movement, hardening, descent, dust, and death constants from bank A5. HP and contact damage remain in Boss Stats.",
        fields = listOf(
            headlessBossBehaviorField("fight_max_x_radius", "Fight Max X Radius", 0xA5E6D7, 0x0040, "Fight Movement", unit = "px"),
            headlessBossBehaviorField("fight_angle_delta", "Fight Angle Delta", 0xA5E6D9, 0x0001, "Fight Movement", signed = true),
            headlessBossBehaviorField("move_open_wait", "Open Wait", 0xA5E74F, 0x0200, "Fight Movement", unit = "frames"),
            headlessBossBehaviorField("move_closed_wait", "Closed Wait", 0xA5E757, 0x00D0, "Fight Movement", unit = "frames"),
            headlessBossBehaviorField("radius_increment", "Radius Increment", 0xA5E765, 0x0008, "Fight Movement", unit = "px"),
            headlessBossBehaviorField("radius_increment_cap", "Radius Increment Cap", 0xA5E768, 0x0030, "Fight Movement", unit = "px"),
            headlessBossBehaviorField("descent_y_speed", "Descent Y Speed", 0xA5EB26, 0x0001, "Descent And Harden", unit = "px/frame"),
            headlessBossBehaviorField("descent_target_y", "Descent Target Y", 0xA5EB2C, 0x0270, "Descent And Harden", unit = "px"),
            headlessBossBehaviorField("descent_initial_radius", "Initial Radius", 0xA5EB3D, 0x0030, "Descent And Harden", unit = "px"),
            headlessBossBehaviorField("descent_initial_angle_delta", "Initial Angle Delta", 0xA5EB44, 0x0001, "Descent And Harden", signed = true),
            headlessBossBehaviorField("descent_initial_angle", "Initial Angle", 0xA5EB4B, 0x00C0, "Descent And Harden", hex = true),
            headlessBossBehaviorField("harden_x", "Harden X", 0xA5E87D, 0x0080, "Descent And Harden", unit = "px"),
            headlessBossBehaviorField("harden_y", "Harden Y", 0xA5E883, 0x0270, "Descent And Harden", unit = "px"),
            headlessBossBehaviorField("hardening_dust_x_mask", "Hardening Dust X Mask", 0xA5E978, 0x007F, "Dust And Death", hex = true),
            headlessBossBehaviorField("hardening_dust_x_offset", "Hardening Dust X Offset", 0xA5E97C, 0x0040, "Dust And Death", unit = "px"),
            headlessBossBehaviorField("hardening_dust_y_mask", "Hardening Dust Y Mask", 0xA5E98C, 0x7F00, "Dust And Death", hex = true),
            headlessBossBehaviorField("hardening_dust_y_offset", "Hardening Dust Y Offset", 0xA5E991, 0x0040, "Dust And Death", unit = "px"),
            headlessBossBehaviorField("dying_explosion_x_mask", "Dying Explosion X Mask", 0xA5E9BB, 0x007F, "Dust And Death", hex = true),
            headlessBossBehaviorField("dying_explosion_x_offset", "Dying Explosion X Offset", 0xA5E9BF, 0x0040, "Dust And Death", unit = "px"),
            headlessBossBehaviorField("dying_explosion_y_mask", "Dying Explosion Y Mask", 0xA5E9CF, 0x3F00, "Dust And Death", hex = true),
            headlessBossBehaviorField("dying_explosion_y_offset", "Dying Explosion Y Offset", 0xA5E9D4, 0x0020, "Dust And Death", unit = "px"),
            headlessBossBehaviorField("death_target_x", "Death Target X", 0xA5EB9F, 0x0080, "Dust And Death", unit = "px"),
            headlessBossBehaviorField("death_target_y", "Death Target Y", 0xA5EBA8, 0x0270, "Dust And Death", unit = "px"),
            headlessBossBehaviorField("death_angle_offset", "Death Angle Offset", 0xA5EBB6, 0x0040, "Dust And Death", hex = true),
            headlessBossBehaviorField("death_speed_magnitude", "Death Speed Magnitude", 0xA5EBC4, 0x0001, "Dust And Death", unit = "speed"),
            headlessBossBehaviorField("death_arrival_target_x", "Death Arrival Target X", 0xA5EC20, 0x0080, "Dust And Death", unit = "px"),
            headlessBossBehaviorField("death_arrival_target_y", "Death Arrival Target Y", 0xA5EC30, 0x0270, "Dust And Death", unit = "px"),
            headlessBossBehaviorField("death_arrival_tolerance", "Death Arrival Tolerance", 0xA5EC27, 0x0008, "Dust And Death", unit = "px", additionalWriteAddresses = listOf(0xA5EC37)),
        ),
    ),
    HeadlessBossBehaviorDefinition(
        configType = CROCOMIRE_CONFIG_TYPE,
        patchId = "config_crocomire",
        name = "Crocomire",
        description = "Edit Crocomire's reaction distances, projectile cadence, screen scroll, bridge collapse, acid, and skeleton constants from bank A4. HP and contact damage remain in Boss Stats.",
        fields = listOf(
            headlessBossBehaviorField("mouth_close_delay", "Mouth Close Delay", 0xA48692, 0x0008, "Damage Reactions", unit = "frames"),
            headlessBossBehaviorField("mouth_close_delay_projectile", "Mouth Close Delay Projectile", 0xA48694, 0x0008, "Damage Reactions", unit = "frames"),
            headlessBossBehaviorField("charged_steps_back", "Charged Steps Back", 0xA48698, 0x0002, "Damage Reactions"),
            headlessBossBehaviorField("missile_steps_back", "Missile Steps Back", 0xA4869A, 0x0001, "Damage Reactions"),
            headlessBossBehaviorField("super_steps_back", "Super Steps Back", 0xA4869C, 0x0003, "Damage Reactions"),
            headlessBossBehaviorField("power_bomb_step_counter", "Power Bomb Step Counter", 0xA4869E, 0x0003, "Damage Reactions"),
            headlessBossBehaviorField("uncharged_mouth_open_timer", "Uncharged Mouth Open Timer", 0xA486A0, 0x0008, "Damage Reactions", unit = "frames"),
            headlessBossBehaviorField("hurt_flash_bonus", "Hurt Flash Bonus", 0xA4BAA5, 0x000E, "Damage Reactions", unit = "frames"),
            headlessBossBehaviorField("power_bomb_flash_bonus", "Power Bomb Flash Bonus", 0xA4B9BE, 0x0004, "Damage Reactions", unit = "frames"),
            headlessBossBehaviorField("wake_distance", "Wake Distance", 0xA48700, 0x00E0, "Fight Flow", unit = "px"),
            headlessBossBehaviorField("near_spike_wall_x", "Near Spike Wall X", 0xA486A2, 0x0300, "Fight Flow", unit = "px"),
            headlessBossBehaviorField("bridge_collapse_x", "Bridge Collapse X", 0xA486A4, 0x0640, "Fight Flow", unit = "px"),
            headlessBossBehaviorField("projectile_random_mask", "Projectile Random Mask", 0xA48757, 0x0FFF, "Fight Flow", hex = true),
            headlessBossBehaviorField("projectile_chance_threshold", "Projectile Chance Threshold", 0xA4875A, 0x0400, "Fight Flow", hex = true),
            headlessBossBehaviorField("projectile_counter_limit", "Projectile Counter Limit", 0xA48788, 0x0012, "Fight Flow"),
            headlessBossBehaviorField("projectile_followup_delay", "Projectile Follow-Up Delay", 0xA4BBCA, 0x00B4, "Fight Flow", unit = "frames"),
            headlessBossBehaviorField("power_bomb_stop_threshold", "Power Bomb Stop Threshold", 0xA48889, 0x0002, "Fight Flow"),
            headlessBossBehaviorField("offscreen_padding", "Offscreen Padding", 0xA48BC1, 0x0080, "Scroll And Bridge", unit = "px", additionalWriteAddresses = listOf(0xA48BFC)),
            headlessBossBehaviorField("bg_scroll_offset", "BG Scroll Offset", 0xA48BD1, 0x0033, "Scroll And Bridge", unit = "px"),
            headlessBossBehaviorField("max_bg_scroll", "Max BG Scroll", 0xA48BDB, 0x011C, "Scroll And Bridge", unit = "px"),
            headlessBossBehaviorField("offscreen_bg_scroll", "Offscreen BG Scroll", 0xA48BE1, 0x0100, "Scroll And Bridge", unit = "px", additionalWriteAddresses = listOf(0xA48BE9)),
            headlessBossBehaviorField("bridge_part_2_x", "Bridge Part 2 X", 0xA48DF1, 0x0620, "Scroll And Bridge", unit = "px"),
            headlessBossBehaviorField("bridge_part_3_x", "Bridge Part 3 X", 0xA48DF6, 0x0630, "Scroll And Bridge", unit = "px"),
            headlessBossBehaviorField("acid_smoke_timer", "Acid Smoke Timer", 0xA49178, 0x0006, "Death Sequence", unit = "frames"),
            headlessBossBehaviorField("acid_smoke_x_mask", "Acid Smoke X Mask", 0xA49182, 0x003F, "Death Sequence", hex = true),
            headlessBossBehaviorField("acid_smoke_y_mask", "Acid Smoke Y Mask", 0xA4919D, 0x1F00, "Death Sequence", hex = true),
            headlessBossBehaviorField("sink_phase_y", "Sink Phase Y", 0xA491D8, 0x0118, "Death Sequence", unit = "px"),
            headlessBossBehaviorField("sink_rest_timer", "Sink Rest Timer", 0xA491E3, 0x0030, "Death Sequence", unit = "frames"),
            headlessBossBehaviorField("skeleton_x_shift", "Skeleton X Shift", 0xA49B1F, 0x0040, "Death Sequence", unit = "px"),
            headlessBossBehaviorField("skeleton_y_shift", "Skeleton Y Shift", 0xA49B29, 0x0015, "Death Sequence", unit = "px"),
            headlessBossBehaviorField("skeleton_y_radius", "Skeleton Y Radius", 0xA49B2F, 0x001C, "Death Sequence", unit = "px"),
            headlessBossBehaviorField("skeleton_x_radius", "Skeleton X Radius", 0xA49B35, 0x0028, "Death Sequence", unit = "px"),
            headlessBossBehaviorField("skeleton_x_velocity_increment", "Skeleton X Velocity Increment", 0xA49B4E, 0x1000, "Death Sequence", hex = true),
            headlessBossBehaviorField("skeleton_x_velocity_cap", "Skeleton X Velocity Cap", 0xA49B5A, 0x0006, "Death Sequence", unit = "speed", additionalWriteAddresses = listOf(0xA49B5F)),
        ),
    ),
    HeadlessBossBehaviorDefinition(
        configType = BOTWOON_CONFIG_TYPE,
        patchId = "config_botwoon",
        name = "Botwoon",
        description = "Edit Botwoon's movement speeds, health thresholds, hole/pathing choices, spit patterns, and death fall constants from bank B3. HP and contact damage remain in Boss Stats.",
        fields = listOf(
            headlessBossBehaviorField("speed_full_health", "Speed Full Health", 0xB394BB, 0x0002, "Speed And Health", unit = "speed"),
            headlessBossBehaviorField("body_travel_full_health", "Body Travel Full Health", 0xB394BD, 0x0018, "Speed And Health", unit = "frames"),
            headlessBossBehaviorField("speed_half_health", "Speed Half Health", 0xB394BF, 0x0003, "Speed And Health", unit = "speed"),
            headlessBossBehaviorField("body_travel_half_health", "Body Travel Half Health", 0xB394C1, 0x0010, "Speed And Health", unit = "frames"),
            headlessBossBehaviorField("speed_quarter_health", "Speed Quarter Health", 0xB394C3, 0x0004, "Speed And Health", unit = "speed"),
            headlessBossBehaviorField("body_travel_quarter_health", "Body Travel Quarter Health", 0xB394C5, 0x000C, "Speed And Health", unit = "frames"),
            headlessBossBehaviorField("palette_threshold_1", "Palette Threshold 1", 0xB3981B, 0x0BB8, "Speed And Health", unit = "hp"),
            headlessBossBehaviorField("palette_threshold_4", "Palette Threshold 4", 0xB39821, 0x0753, "Speed And Health", unit = "hp"),
            headlessBossBehaviorField("palette_threshold_8", "Palette Threshold 8", 0xB39829, 0x0177, "Speed And Health", unit = "hp"),
            headlessBossBehaviorField("body_projectile_index", "Body Projectile Index", 0xB395B4, 0x0018, "Init And Pathing"),
            headlessBossBehaviorField("initial_timer", "Initial Timer", 0xB395E8, 0x0100, "Init And Pathing", unit = "frames"),
            headlessBossBehaviorField("initial_head_hidden_flag", "Initial Head Hidden Flag", 0xB395FC, 0x0001, "Init And Pathing", hex = true),
            headlessBossBehaviorField("initial_target_history_index", "Initial Target History Index", 0xB3960B, 0xFFFF, "Init And Pathing", signed = true),
            headlessBossBehaviorField("initial_target_hole_index", "Initial Target Hole Index", 0xB39612, 0x0000, "Init And Pathing", hex = true),
            headlessBossBehaviorField("palette_offset_base", "Palette Offset Base", 0xB39661, 0x0100, "Init And Pathing", hex = true),
            headlessBossBehaviorField("leave_action_random_mask", "Leave Action Random Mask", 0xB398C6, 0x000E, "Init And Pathing", hex = true),
            headlessBossBehaviorField("path_destination_random_mask", "Path Destination Random Mask", 0xB39948, 0x0018, "Init And Pathing", hex = true),
            headlessBossBehaviorField("spit_timer", "Spit Timer", 0xB39923, 0x0030, "Spit", unit = "frames"),
            headlessBossBehaviorField("spit_speed_full_health", "Spit Speed Full Health", 0xB39E77, 0x0002, "Spit", unit = "speed"),
            headlessBossBehaviorField("spit_speed_half_health", "Spit Speed Half Health", 0xB39E79, 0x0003, "Spit", unit = "speed"),
            headlessBossBehaviorField("spit_speed_quarter_health", "Spit Speed Quarter Health", 0xB39E7B, 0x0004, "Spit", unit = "speed"),
            headlessBossBehaviorField("spit_aim_offset", "Spit Aim Offset", 0xB39E90, 0x0010, "Spit", hex = true),
            headlessBossBehaviorField("spit_angle_origin", "Spit Angle Origin", 0xB39EB5, 0x0040, "Spit", hex = true),
            headlessBossBehaviorField("spit_angle_wrap", "Spit Angle Wrap", 0xB39EC0, 0x0100, "Spit", hex = true),
            headlessBossBehaviorField("five_spit_spread_start", "Five-Spit Spread Start", 0xB39EF0, 0x0020, "Spit", hex = true),
            headlessBossBehaviorField("five_spit_count", "Five-Spit Count", 0xB39EF9, 0x0005, "Spit"),
            headlessBossBehaviorField("spit_angle_step", "Spit Angle Step", 0xB39F19, 0x0010, "Spit", hex = true, additionalWriteAddresses = listOf(0xB39F66)),
            headlessBossBehaviorField("three_spit_spread_start", "Three-Spit Spread Start", 0xB39F3D, 0x0010, "Spit", hex = true),
            headlessBossBehaviorField("three_spit_count", "Three-Spit Count", 0xB39F46, 0x0003, "Spit"),
            headlessBossBehaviorField("pre_death_delay", "Pre-Death Delay", 0xB39A53, 0x0100, "Death", unit = "frames"),
            headlessBossBehaviorField("fall_ground_y", "Fall Ground Y", 0xB39A87, 0x00C8, "Death", unit = "px", additionalWriteAddresses = listOf(0xB39A8C)),
            headlessBossBehaviorField("fall_speed_index_increment", "Fall Speed Index Increment", 0xB39AC3, 0x00C0, "Death", hex = true),
        ),
    ),
    HeadlessBossBehaviorDefinition(
        configType = TORIZO_CONFIG_TYPE,
        patchId = "config_torizo",
        name = "Torizo / Golden Torizo",
        description = "Edit Bomb Torizo and Golden Torizo spawn, jump, landing, attack, and low-health constants from bank AA. HP and contact damage remain in Boss Stats.",
        fields = listOf(
            headlessBossBehaviorField("bomb_initial_x", "Bomb Initial X", 0xAAC95F, 0x00DB, "Init And Collision", unit = "px"),
            headlessBossBehaviorField("golden_initial_x", "Golden Initial X", 0xAAC961, 0x01A8, "Init And Collision", unit = "px"),
            headlessBossBehaviorField("bomb_initial_y", "Bomb Initial Y", 0xAAC963, 0x00B3, "Init And Collision", unit = "px"),
            headlessBossBehaviorField("golden_initial_y", "Golden Initial Y", 0xAAC965, 0x0090, "Init And Collision", unit = "px"),
            headlessBossBehaviorField("bomb_x_radius", "Bomb X Radius", 0xAAC96F, 0x0012, "Init And Collision", unit = "px"),
            headlessBossBehaviorField("golden_x_radius", "Golden X Radius", 0xAAC971, 0x0012, "Init And Collision", unit = "px"),
            headlessBossBehaviorField("bomb_y_radius", "Bomb Y Radius", 0xAAC973, 0x0030, "Init And Collision", unit = "px"),
            headlessBossBehaviorField("golden_y_radius", "Golden Y Radius", 0xAAC975, 0x0029, "Init And Collision", unit = "px"),
            headlessBossBehaviorField("forward_jump_left_x_speed", "Forward Jump Left X", 0xAAC210, 0xFE00, "Jump And Landing", unit = "speed", signed = true),
            headlessBossBehaviorField("forward_jump_right_x_speed", "Forward Jump Right X", 0xAAC215, 0x0200, "Jump And Landing", unit = "speed", signed = true),
            headlessBossBehaviorField("forward_jump_y_speed", "Forward Jump Y", 0xAAC21B, 0xFA40, "Jump And Landing", unit = "speed", signed = true),
            headlessBossBehaviorField("forward_jump_y_accel", "Forward Jump Y Accel", 0xAAC221, 0x0028, "Jump And Landing", unit = "subpx/frame"),
            headlessBossBehaviorField("back_jump_left_x_speed", "Back Jump Left X", 0xAAC233, 0x0300, "Jump And Landing", unit = "speed", signed = true),
            headlessBossBehaviorField("back_jump_right_x_speed", "Back Jump Right X", 0xAAC238, 0xFD00, "Jump And Landing", unit = "speed", signed = true),
            headlessBossBehaviorField("back_jump_y_speed", "Back Jump Y", 0xAAC23E, 0xFB80, "Jump And Landing", unit = "speed", signed = true),
            headlessBossBehaviorField("back_jump_y_accel", "Back Jump Y Accel", 0xAAC244, 0x0028, "Jump And Landing", unit = "subpx/frame"),
            headlessBossBehaviorField("fall_reset_y_speed", "Fall Reset Y Speed", 0xAAC7B8, 0x0100, "Jump And Landing", unit = "speed", additionalWriteAddresses = listOf(0xAAC81F, 0xAAC86D, 0xAAD64F)),
            headlessBossBehaviorField("landing_earthquake_type", "Landing Earthquake Type", 0xAAC873, 0x0004, "Jump And Landing", hex = true),
            headlessBossBehaviorField("landing_earthquake_timer", "Landing Earthquake Timer", 0xAAC879, 0x0020, "Jump And Landing", unit = "frames"),
            headlessBossBehaviorField("low_health_drool_threshold", "Low Health Threshold", 0xAAC35F, 0x015E, "Bomb Torizo", unit = "hp", additionalWriteAddresses = listOf(0xAAC636, 0xAAC70B)),
            headlessBossBehaviorField("face_blow_threshold", "Face Blow Threshold", 0xAAC72C, 0x0064, "Bomb Torizo", unit = "hp"),
            headlessBossBehaviorField("bomb_turn_timer", "Turn Timer", 0xAAC4B4, 0x0048, "Bomb Torizo", unit = "frames", additionalWriteAddresses = listOf(0xAAC529)),
            headlessBossBehaviorField("close_swipe_distance", "Close Swipe Distance", 0xAAC568, 0x0038, "Bomb Torizo", unit = "px"),
            headlessBossBehaviorField("bomb_back_jump_distance", "Back Jump Distance", 0xAAC58C, 0x0020, "Bomb Torizo", unit = "px"),
            headlessBossBehaviorField("bomb_missile_threshold", "Missile Threshold", 0xAAC5B1, 0x0005, "Bomb Torizo", unit = "missiles"),
            headlessBossBehaviorField("bomb_attack_selection_mask", "Attack Selection Mask", 0xAAC5BD, 0x0008, "Bomb Torizo", hex = true),
            headlessBossBehaviorField("golden_wake_y", "Wake Samus Y", 0xAAD5C3, 0x0140, "Golden Torizo", unit = "px"),
            headlessBossBehaviorField("golden_wake_x", "Wake Samus X", 0xAAD5CB, 0x0170, "Golden Torizo", unit = "px"),
            headlessBossBehaviorField("golden_turn_timer", "Turn Timer", 0xAAD591, 0x0010, "Golden Torizo", unit = "frames"),
            headlessBossBehaviorField("golden_morph_behind_min", "Morph Behind Min", 0xAAD3F0, 0x0004, "Golden Torizo", unit = "px"),
            headlessBossBehaviorField("golden_morph_behind_max", "Morph Behind Max", 0xAAD3F9, 0x0028, "Golden Torizo", unit = "px"),
            headlessBossBehaviorField("golden_front_attack_min", "Front Attack Min", 0xAAD44B, 0x0020, "Golden Torizo", unit = "px"),
            headlessBossBehaviorField("golden_front_attack_max", "Front Attack Max", 0xAAD454, 0x0060, "Golden Torizo", unit = "px"),
            headlessBossBehaviorField("golden_front_attack_chance_mask", "Front Attack Chance Mask", 0xAAD461, 0x0110, "Golden Torizo", hex = true),
            headlessBossBehaviorField("golden_low_health_attack_threshold", "Low Health Attack", 0xAAD475, 0x0788, "Golden Torizo", unit = "hp"),
            headlessBossBehaviorField("golden_low_health_chance_mask", "Low Health Chance Mask", 0xAAD481, 0x0102, "Golden Torizo", hex = true),
            headlessBossBehaviorField("golden_high_health_stunned_threshold", "High Health Stunned", 0xAAD49C, 0x2A30, "Golden Torizo", unit = "hp"),
            headlessBossBehaviorField("golden_forward_jump_distance", "Forward Jump Distance", 0xAAD4BB, 0x0070, "Golden Torizo", unit = "px"),
            headlessBossBehaviorField("golden_space_jump_counter", "Space Jump Counter", 0xAAD4C9, 0x0168, "Golden Torizo", unit = "frames"),
            headlessBossBehaviorField("golden_forward_jump_chance_mask", "Forward Jump Chance Mask", 0xAAD4DD, 0x0101, "Golden Torizo", hex = true),
            headlessBossBehaviorField("golden_back_jump_step_threshold", "Back Jump Step Threshold", 0xAAD502, 0x0008, "Golden Torizo"),
            headlessBossBehaviorField("golden_back_jump_distance", "Back Jump Distance", 0xAAD507, 0x0020, "Golden Torizo", unit = "px"),
            headlessBossBehaviorField("golden_missile_threshold", "Missile Threshold", 0xAAD533, 0x0020, "Golden Torizo", unit = "missiles"),
            headlessBossBehaviorField("golden_attack_selection_mask", "Attack Selection Mask", 0xAAD53F, 0x0008, "Golden Torizo", hex = true),
        ),
    ),
    HeadlessBossBehaviorDefinition(
        configType = MOTHER_BRAIN_CONFIG_TYPE,
        patchId = "config_mother_brain",
        name = "Mother Brain",
        description = "Edit source-backed phase one, phase two, blue-ring, rainbow beam, laser, and death-sequence constants from bank A9. HP and contact damage remain in Boss Stats.",
        fields = listOf(
            headlessBossBehaviorField("phase1_samus_x_gate", "Phase 1 Samus X Gate", 0xA987F5, 0x00EC, "Phase One And Fake Death", unit = "px"),
            headlessBossBehaviorField("fake_death_initial_pause", "Fake Death Initial Pause", 0xA98824, 0x0040, "Phase One And Fake Death", unit = "frames"),
            headlessBossBehaviorField("fake_death_lock_pause", "Fake Death Lock Pause", 0xA98848, 0x0020, "Phase One And Fake Death", unit = "frames"),
            headlessBossBehaviorField("fake_death_music_pause", "Fake Death Music Pause", 0xA98867, 0x000C, "Phase One And Fake Death", unit = "frames"),
            headlessBossBehaviorField("fake_death_unlock_pause", "Fake Death Unlock Pause", 0xA9887F, 0x0008, "Phase One And Fake Death", unit = "frames"),
            headlessBossBehaviorField("grey_transition_timer", "Grey Transition Timer", 0xA988B8, 0x0008, "Phase One And Fake Death", unit = "frames"),
            headlessBossBehaviorField("fake_death_explosion_timer", "Fake Death Explosion Timer", 0xA988EA, 0x0008, "Phase One And Fake Death", unit = "frames"),
            headlessBossBehaviorField("fake_death_explosion_wrap", "Explosion Index Wrap", 0xA988F8, 0x0007, "Phase One And Fake Death"),
            headlessBossBehaviorField("fake_death_smoke_threshold", "Smoke Chance Threshold", 0xA98912, 0x4000, "Phase One And Fake Death", hex = true),
            headlessBossBehaviorField("tube_projectile_min_free_slots", "Tube Min Free Slots", 0xA9895B, 0x0004, "Phase One And Fake Death"),
            headlessBossBehaviorField("second_phase_low_health_threshold", "Low Health Threshold", 0xA9B61E, 0x1194, "Phase Two Attacks", unit = "hp"),
            headlessBossBehaviorField("high_health_attack_roll_threshold", "High-Health Attack Roll", 0xA9B626, 0x1000, "Phase Two Attacks", hex = true),
            headlessBossBehaviorField("low_health_walk_roll_threshold", "Low-Health Walk Roll", 0xA9B638, 0x2000, "Phase Two Attacks", hex = true),
            headlessBossBehaviorField("low_health_attack_roll_threshold", "Low-Health Attack Roll", 0xA9B640, 0xA000, "Phase Two Attacks", hex = true),
            headlessBossBehaviorField("attack_cooldown", "Attack Cooldown", 0xA9B65B, 0x0040, "Phase Two Attacks", unit = "frames"),
            headlessBossBehaviorField("attack_y_proximity_offset", "Attack Y Offset", 0xA9B674, 0x0004, "Phase Two Attacks", unit = "px"),
            headlessBossBehaviorField("attack_y_proximity_window", "Attack Y Window", 0xA9B681, 0x0020, "Phase Two Attacks", unit = "px"),
            headlessBossBehaviorField("max_active_bombs", "Max Active Bombs", 0xA9B6BE, 0x0001, "Phase Two Attacks", additionalWriteAddresses = listOf(0xA9B71D)),
            headlessBossBehaviorField("bomb_crouch_roll_threshold", "Bomb Crouch Roll", 0xA9B785, 0xFF80, "Phase Two Attacks", hex = true),
            headlessBossBehaviorField("bomb_near_target_x", "Bomb Near Target X", 0xA9B78A, 0x0040, "Phase Two Attacks", unit = "px"),
            headlessBossBehaviorField("bomb_far_target_x", "Bomb Far Target X", 0xA9B792, 0x0060, "Phase Two Attacks", unit = "px"),
            headlessBossBehaviorField("bomb_post_fire_delay", "Bomb Post-Fire Delay", 0xA9B7E2, 0x002C, "Phase Two Attacks", unit = "frames"),
            headlessBossBehaviorField("blue_ring_shitroid_x_offset", "Shitroid Aim X Offset", 0xA99E47, 0x000A, "Blue Ring Projectiles", unit = "px"),
            headlessBossBehaviorField("blue_ring_shitroid_y_offset", "Shitroid Aim Y Offset", 0xA99E54, 0x0010, "Blue Ring Projectiles", unit = "px"),
            headlessBossBehaviorField("blue_ring_samus_x_offset", "Samus Aim X Offset", 0xA99E66, 0x000A, "Blue Ring Projectiles", unit = "px"),
            headlessBossBehaviorField("blue_ring_samus_y_offset", "Samus Aim Y Offset", 0xA99E73, 0x0010, "Blue Ring Projectiles", unit = "px"),
            headlessBossBehaviorField("blue_ring_angle_flip_origin", "Angle Flip Origin", 0xA99E7D, 0x0080, "Blue Ring Projectiles", hex = true, maxValue = 0x00FF),
            headlessBossBehaviorField("shitroid_attack_cap", "Shitroid Attack Cap", 0xA99EA9, 0x000C, "Blue Ring Projectiles", maxValue = 0x000C, additionalWriteAddresses = listOf(0xA99EAE)),
            headlessBossBehaviorField("laser_fast_neck_delta", "Laser Fast Neck Delta", 0xA9B826, 0x0200, "Laser And Rainbow Beam", unit = "speed"),
            headlessBossBehaviorField("laser_fast_position_timer", "Laser Fast Position Timer", 0xA9B833, 0x0004, "Laser And Rainbow Beam", unit = "frames"),
            headlessBossBehaviorField("laser_slow_neck_delta", "Laser Slow Neck Delta", 0xA9B840, 0x0100, "Laser And Rainbow Beam", unit = "speed"),
            headlessBossBehaviorField("laser_finish_timer", "Laser Finish Timer", 0xA9B85D, 0x0010, "Laser And Rainbow Beam", unit = "frames"),
            headlessBossBehaviorField("laser_x_offset", "Laser X Offset", 0xA99F53, 0x0010, "Laser And Rainbow Beam", unit = "px"),
            headlessBossBehaviorField("laser_y_offset", "Laser Y Offset", 0xA99F5C, 0x0004, "Laser And Rainbow Beam", unit = "px"),
            headlessBossBehaviorField("laser_projectile_param", "Laser Projectile Param", 0xA99F61, 0x0001, "Laser And Rainbow Beam", hex = true),
            headlessBossBehaviorField("rainbow_extend_timer", "Rainbow Extend Timer", 0xA9B914, 0x0100, "Laser And Rainbow Beam", unit = "frames"),
            headlessBossBehaviorField("rainbow_retract_target_x", "Rainbow Retract Target X", 0xA9B92C, 0x0028, "Laser And Rainbow Beam", unit = "px"),
            headlessBossBehaviorField("rainbow_charge_timer", "Rainbow Charge Timer", 0xA9B93A, 0x0100, "Laser And Rainbow Beam", unit = "frames"),
            headlessBossBehaviorField("rainbow_start_firing_timer", "Rainbow Start Timer", 0xA9B970, 0x0010, "Laser And Rainbow Beam", unit = "frames"),
            headlessBossBehaviorField("rainbow_initial_width", "Rainbow Initial Width", 0xA9B995, 0x0200, "Laser And Rainbow Beam", hex = true, additionalWriteAddresses = listOf(0xA9BA77)),
            headlessBossBehaviorField("rainbow_samus_low_health", "Samus Low Health", 0xA9B9CC, 0x02BC, "Laser And Rainbow Beam", unit = "hp"),
            headlessBossBehaviorField("rainbow_sound_queue_count", "Rainbow Sound Queue Count", 0xA9B9D8, 0x0006, "Laser And Rainbow Beam"),
            headlessBossBehaviorField("rainbow_wall_quake_type", "Wall Quake Type", 0xA9BA15, 0x0008, "Laser And Rainbow Beam", hex = true),
            headlessBossBehaviorField("rainbow_wall_quake_timer", "Wall Quake Timer", 0xA9BA1B, 0x0008, "Laser And Rainbow Beam", unit = "frames"),
            headlessBossBehaviorField("rainbow_drain_timer", "Rainbow Drain Timer", 0xA9BA2E, 0x012B, "Laser And Rainbow Beam", unit = "frames"),
            headlessBossBehaviorField("death_back_room_target_x", "Back Room Target X", 0xA9AEFE, 0x0028, "Death And Escape", unit = "px"),
            headlessBossBehaviorField("death_idle_timer", "Death Idle Timer", 0xA9AF0D, 0x0080, "Death And Escape", unit = "frames"),
            headlessBossBehaviorField("death_middle_target_x", "Middle Target X", 0xA9AF28, 0x0060, "Death And Escape", unit = "px"),
            headlessBossBehaviorField("death_neck_angle_delta", "Death Neck Angle Delta", 0xA9AF41, 0x0500, "Death And Escape", unit = "speed"),
            headlessBossBehaviorField("death_disable_effects_delay", "Disable Effects Delay", 0xA9AF4E, 0x0020, "Death And Escape", unit = "frames"),
            headlessBossBehaviorField("final_explosions_timer", "Final Explosions Timer", 0xA9B00D, 0x0010, "Death And Escape", unit = "frames"),
            headlessBossBehaviorField("smoky_explosion_count", "Smoky Explosion Count", 0xA9B028, 0x0002, "Death And Escape"),
            headlessBossBehaviorField("smoky_explosion_interval", "Smoky Explosion Interval", 0xA9B02D, 0x0010, "Death And Escape", unit = "frames"),
            headlessBossBehaviorField("mixed_explosion_count", "Mixed Explosion Count", 0xA9B037, 0x0004, "Death And Escape"),
            headlessBossBehaviorField("mixed_explosion_interval", "Mixed Explosion Interval", 0xA9B03C, 0x0008, "Death And Escape", unit = "frames"),
            headlessBossBehaviorField("brain_fall_acceleration", "Brain Fall Acceleration", 0xA9B132, 0x0020, "Death And Escape", unit = "subpx/frame"),
            headlessBossBehaviorField("brain_ground_y", "Brain Ground Y", 0xA9B140, 0x00C4, "Death And Escape", unit = "px"),
            headlessBossBehaviorField("corpse_tiles_delay", "Corpse Tiles Delay", 0xA9B16D, 0x0020, "Death And Escape", unit = "frames"),
            headlessBossBehaviorField("corpse_fade_step_timer", "Corpse Fade Step Timer", 0xA9B19F, 0x0010, "Death And Escape", unit = "frames"),
            headlessBossBehaviorField("corpse_tip_timer", "Corpse Tip Timer", 0xA9B1B2, 0x0100, "Death And Escape", unit = "frames"),
            headlessBossBehaviorField("escape_music_text_delay", "Escape Music/Text Delay", 0xA9B20C, 0x0014, "Death And Escape", unit = "frames"),
            headlessBossBehaviorField("escape_earthquake_timer", "Escape Earthquake Timer", 0xA9B290, 0xFFFF, "Death And Escape", hex = true),
            headlessBossBehaviorField("escape_text_delay", "Escape Text Delay", 0xA9B2BD, 0x0020, "Death And Escape", unit = "frames"),
            headlessBossBehaviorField("escape_door_start_delay", "Escape Door Start Delay", 0xA9B2F3, 0x0020, "Death And Escape", unit = "frames"),
            headlessBossBehaviorField("escape_door_explosion_interval", "Escape Door Explosion Interval", 0xA9B350, 0x0004, "Death And Escape", unit = "frames"),
            headlessBossBehaviorField("escape_door_index_wrap", "Escape Door Index Wrap", 0xA9B35F, 0x0003, "Death And Escape"),
        ),
    ),
)

internal val HEADLESS_BOSS_BEHAVIOR_BY_CONFIG_TYPE: Map<String, HeadlessBossBehaviorDefinition> =
    HEADLESS_BOSS_BEHAVIOR_DEFINITIONS.associateBy { it.configType }

internal val HEADLESS_BOSS_BEHAVIOR_CONFIG_TYPES: Set<String> = HEADLESS_BOSS_BEHAVIOR_BY_CONFIG_TYPE.keys

internal fun HeadlessBossBehaviorField.logicalDefaultValue(): Int = logicalValue(defaultValue)

internal fun HeadlessBossBehaviorField.logicalValue(storedValue: Int): Int {
    val word = storedValue and 0xFFFF
    return if (signed && word > 0x7FFF) word - 0x10000 else word
}

internal fun HeadlessBossBehaviorField.storedValue(logicalValue: Int): Int =
    if (signed && logicalValue < 0) logicalValue + 0x10000 else logicalValue

internal fun HeadlessBossBehaviorField.logicalMinValue(): Int =
    minValue ?: when {
        signed && unit in setOf("px/frame", "steps/frame") -> -255
        signed -> -32768
        else -> 0
    }

internal fun HeadlessBossBehaviorField.logicalMaxValue(): Int {
    val inferred = maxValue ?: when {
        hex -> 0xFFFF
        unit == "hp" -> 32767
        unit == "frames" -> 32767
        unit == "px" -> 4095
        unit == "missiles" -> 999
        unit == "damage" -> 9999
        unit in setOf("px/frame", "steps/frame") -> 255
        unit == "subpx/frame" -> 32767
        unit == "speed" -> 32767
        signed -> 32767
        else -> 0xFFFF
    }
    return maxOf(inferred, logicalDefaultValue())
}

internal fun coerceHeadlessBossBehaviorValue(field: HeadlessBossBehaviorField, storedValue: Int): Int {
    val logical = field.logicalValue(storedValue).coerceIn(field.logicalMinValue(), field.logicalMaxValue())
    return field.storedValue(logical).coerceIn(0, 0xFFFF)
}
