package com.supermetroid.editor.asm

import com.supermetroid.editor.data.SmPatch
import com.supermetroid.editor.rom.RomWriteIntent
import com.supermetroid.editor.rom.RomWriteKind
import com.supermetroid.editor.rom.RomWritePlanReport

internal enum class PatchImplementationBackend {
    ROM_WRITES,
    ASM_GENERATED_OVERLAY,
    ASM_CURATED_MODULE,
}

internal data class PatchBackendSupport(
    val rom: PatchImplementationBackend = PatchImplementationBackend.ROM_WRITES,
    val asm: PatchImplementationBackend? = null,
)

/**
 * Explicit migration table for patches with a source-build implementation.
 * A build selects one implementation; entries here never cause both backends
 * to mutate the same bytes. New patch families graduate one at a time.
 */
internal object AsmPatchBackendRegistry {
    private val sourceConfigTypes = mapOf(
        "samus_physics" to PatchImplementationBackend.ASM_GENERATED_OVERLAY,
    )

    fun supportFor(patch: SmPatch): PatchBackendSupport = PatchBackendSupport(
        asm = patch.configType?.let(sourceConfigTypes::get),
    )

    fun sourceOwners(patches: List<SmPatch>): Set<String> = patches.asSequence()
        .filter(SmPatch::enabled)
        .filter { supportFor(it).asm != null }
        .mapTo(linkedSetOf()) { "patch:${it.id}" }
}

internal data class AsmGeneratedPatchClaim(
    val owner: String,
    val label: String,
    val pcOffset: Int,
    val bytes: ByteArray,
) {
    val length: Int get() = bytes.size
    val endExclusive: Int get() = pcOffset + length

    override fun equals(other: Any?): Boolean =
        other is AsmGeneratedPatchClaim &&
            owner == other.owner &&
            label == other.label &&
            pcOffset == other.pcOffset &&
            bytes.contentEquals(other.bytes)

    override fun hashCode(): Int {
        var result = owner.hashCode()
        result = 31 * result + label.hashCode()
        result = 31 * result + pcOffset
        result = 31 * result + bytes.contentHashCode()
        return result
    }
}

internal data class AsmPatchMaterialization(
    val source: String,
    val claims: List<AsmGeneratedPatchClaim>,
    val eligibleWrites: Int,
    val skippedWrites: Int,
) {
    val isEmpty: Boolean get() = claims.isEmpty()

    companion object {
        val EMPTY = AsmPatchMaterialization("", emptyList(), 0, 0)
    }
}

/** Builds a temporary Asar overlay from already validated patch write intents. */
internal class AsmSourcePatchMaterializer {
    fun materialize(
        report: RomWritePlanReport,
        sourceOwners: Set<String>,
        compiledRomSize: Int,
    ): AsmPatchMaterialization {
        if (sourceOwners.isEmpty()) return AsmPatchMaterialization.EMPTY
        val candidates = report.writes.filter { write ->
            write.owner in sourceOwners && write.kind in MATERIALIZABLE_KINDS
        }
        val allocatedRanges = report.writes
            .filter { it.kind == RomWriteKind.ALLOCATION }
            .map { it.offset..it.endInclusive }
        val claims = mutableListOf<AsmGeneratedPatchClaim>()
        var skipped = 0

        val indexedCandidates = candidates.withIndex().toList()
        indexedCandidates.groupBy { it.value.owner }.forEach { (_, ownerEntries) ->
            val ownerIsSafe = ownerEntries.all { entry ->
                val write = entry.value
                val overlapsAllocation = allocatedRanges.any { allocated -> write.overlaps(allocated) }
                val overlapsPatch = indexedCandidates.any { other ->
                    other.index != entry.index && write.overlaps(other.value)
                }
                write.offset >= 0 &&
                    write.endInclusive < compiledRomSize &&
                    pcToSnesLoRom(write.offset) != null &&
                    !overlapsAllocation &&
                    !overlapsPatch
            }
            if (!ownerIsSafe) {
                skipped += ownerEntries.size
                return@forEach
            }
            ownerEntries.forEach { entry ->
                val write = entry.value
                claims += AsmGeneratedPatchClaim(
                    owner = write.owner,
                    label = write.label,
                    pcOffset = write.offset,
                    bytes = ByteArray(write.bytes.size) { write.bytes[it].toByte() },
                )
            }
        }

        return AsmPatchMaterialization(
            source = renderSource(claims),
            claims = claims,
            eligibleWrites = candidates.size,
            skippedWrites = skipped,
        )
    }

    private fun renderSource(claims: List<AsmGeneratedPatchClaim>): String = buildString {
        if (claims.isEmpty()) return@buildString
        appendLine("; Generated by SMEDIT for this build. Do not edit: the GUI/project model is authoritative.")
        appendLine("; Patch families opt into this backend explicitly; unsupported patches remain post-compile.")
        claims.forEach { claim ->
            val snesAddress = checkNotNull(pcToSnesLoRom(claim.pcOffset))
            appendLine()
            appendLine("; ${claim.owner} · ${claim.label.replace('\n', ' ')}")
            appendLine("org \$${snesAddress.toString(16).uppercase().padStart(6, '0')}")
            claim.bytes.asList().chunked(BYTES_PER_LINE).forEach { row ->
                append("db ")
                appendLine(row.joinToString(",") { "\$${(it.toInt() and 0xFF).toString(16).uppercase().padStart(2, '0')}" })
            }
        }
    }

    private fun RomWriteIntent.overlaps(other: RomWriteIntent): Boolean =
        offset <= other.endInclusive && other.offset <= endInclusive

    private fun RomWriteIntent.overlaps(other: IntRange): Boolean =
        offset <= other.last && other.first <= endInclusive

    private companion object {
        const val BYTES_PER_LINE = 16
        val MATERIALIZABLE_KINDS = setOf(RomWriteKind.FIXED_PATCH, RomWriteKind.CONFIG)
    }
}
