package com.supermetroid.editor.rom

import org.junit.jupiter.api.Tag
import org.junit.jupiter.api.Test
import kotlin.test.assertEquals
import kotlin.test.assertFailsWith

class SourceSymbolParityTest {

    @Test
    fun `WLA parser reads labels and stops before later sections`() {
        val catalog = WlaSymbolCatalog.parse(
            listOf(
                "; generated by asar",
                "[labels]",
                "8F:92FD RoomHeader_Parlor",
                "92:808D SamusSpritemapTable",
                "92:808D SamusSpritemapTable_Alias",
                "",
                "[source files]",
                "0000 deadbeef src/main.asm",
            )
        )

        assertEquals(3, catalog.symbols.size)
        assertEquals(0x8F92FD, catalog.requireUnique("RoomHeader_Parlor").snesAddress)
        assertEquals(2, catalog.at(0x92808D).size)
    }

    @Test
    fun `WLA parser rejects malformed label records`() {
        assertFailsWith<IllegalStateException> {
            WlaSymbolCatalog.parse(listOf("[labels]", "not-a-label"))
        }
    }

    @Tag("parity")
    @Test
    fun `SMEDIT address constants match named source symbols`() {
        val catalog = TestRomHelper.requireSymbolCatalog()
        val expectations = linkedMapOf(
            "Tileset_Table_0_UpperCrateria" to TileGraphics.TILESET_TABLE_SNES,
            "RoomHeader_Kraid" to KraidSpritemap.KRAID_ROOM_SNES,
            "Background_Brinstar_1A_Kraid_Upper" to KraidSpritemap.UPPER_BG2_TILEMAP_SNES,
            "Background_Brinstar_1A_Kraid_Lower_0" to KraidSpritemap.LOWER_BG2_TILEMAP_SNES,
            "RoomHeader_Phantoon" to PhantoonSpritemap.PHANTOON_ROOM_SNES,
            "UNUSED_Palette_Phantoon_A7CA21" to PhantoonSpritemap.PALETTE_SNES,
            "SamusTilesAnimation_AnimationDefinitionPointers" to SamusSpriteDecoder.FRAME_PROG_PTRS,
            "SamusTopHalfTilesAnimation_TilesDefinitionPointers" to SamusSpriteDecoder.TOP_DMA_PTRS,
            "SamusBottomHalfTilesAnimation_TilesDefinitionPointers" to SamusSpriteDecoder.BOT_DMA_PTRS,
            "SamusSpritemapTableIndices_TopHalf" to SamusSpriteDecoder.UPPER_TILEMAP_INDEX,
            "SamusSpritemapTableIndices_BottomHalf" to SamusSpriteDecoder.LOWER_TILEMAP_INDEX,
            "SamusSpritemapTable" to SamusSpriteDecoder.TILEMAP_PTRS,
        )

        expectations.forEach { (symbolName, smeditAddress) ->
            val sourceAddress = catalog.requireUnique(symbolName).snesAddress
            assertEquals(
                sourceAddress,
                smeditAddress,
                "$symbolName drifted: source=${sourceAddress.toSnes()} SMEDIT=${smeditAddress.toSnes()}",
            )
        }
    }

    private fun Int.toSnes(): String = "%02X:%04X".format((this ushr 16) and 0xFF, this and 0xFFFF)
}
